version: '2'
services:
  webapp:
    image: libapps-admin.uncw.edu:8000/randall-dev/d8-staff/drupal8base:latest
    environment:
      DRUPAL_SALT: 70xtRzNbXltiqiW-2B74R-Cy7hH8tr71ISHr-b3MgqDxC0SsfOuNvXT7ZrkxNxBiU4zgtKDDgQ
      MYSQL_DATABASE: d8staff
      MYSQL_HOST: db
      MYSQL_PASSWORD: CHANGEME
      MYSQL_ROOT_PASSWORD: CHANGEME
      MYSQL_USER: drupaluser
      WEB_GROUP: www-data
      WEB_USER: www-data
    stdin_open: true
    volumes:
    - /home/randall/volumes/d8staff/sync:/drupal_sync
    - /home/randall/volumes/d8staff/themes:/drupal_app/web/themes/contrib
    - /home/randall/volumes/d8staff/modules/custom:/drupal_app/web/modules/custom
    - drupal_data:/drupal_app
    tty: true
    labels:
      io.rancher.container.pull_image: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    stdin_open: true
    tty: true
  nginx:
    image: nginx:1.16.0
    environment:
      NGINX_SERVER_ROOT: /drupal_app/web
      WEB_GROUP: www-data
      WEB_USER: www-data
    stdin_open: true
    volumes:
    - /home/randall/volumes/d8staff/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - drupal_data:/drupal_app
    tty: true
    labels:
      io.rancher.container.pull_image: always
  db-backup:
    image: libapps-admin.uncw.edu:8000/randall-dev/test-sidekick
    environment:
      DB_HOST: db
      DB_NAMES: db
      ROOT_PASSWORD: CHANGEME
    stdin_open: true
    volumes:
    - /home/randall/volumes/backups/Backups/d8staff:/backups
    tty: true
    labels:
      io.rancher.container.pull_image: always
  db:
    image: mysql:8.0.16
    environment:
      MYSQL_PASSWORD: CHANGEME
      MYSQL_ROOT_PASSWORD: CHANGEME
      MYSQL_USER: drupaluser
      TZ: America/New_York
    stdin_open: true
    volumes:
    - /home/randall/volumes/d8staff/mysql:/var/lib/mysql
    - /home/randall/volumes/d8staff/db_autoimport:/docker-entrypoint-initdb.d/
    tty: true
    command:
    - --default-authentication-plugin=mysql_native_password
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: db-backup
