version: '2'
services:
  webapp:
    image: libapps-admin.uncw.edu:8000/randall-dev/d8-staff/drupal8base:latest
    environment:
      DRUPAL_SALT: 70xtRzNbXltiqiW-2B74R-Cy7hH8tr71ISHr-b3MgqDxC0SsfOuNvXT7ZrkxNxBiU4zgtKDDgQ
      MYSQL_DATABASE: d8staff
      MYSQL_HOST: db
      MYSQL_PASSWORD: CHANGEME
      MYSQL_ROOT_PASSWORD: CHANGEME
      MYSQL_USER: drupaluser
      WEB_GROUP: www-data
      WEB_USER: www-data
    volumes:
    - /home/randall/volumes/d8-staff/private:/var/www/html/private
    - /home/randall/volumes/d8-staff/files:/var/www/html/web/sites/default/files
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      PMA_HOST: db
  db-backup:
    image: libapps-admin.uncw.edu:8000/randall-dev/test-sidekick
    environment:
      DB_HOST: db
      DB_NAMES: db
      ROOT_PASSWORD: CHANGEME
    volumes:
    - /home/randall/volumes/backups/Backups/d8-staff:/backups
  db:
    image: mysql:8.0.16
    environment:
      MYSQL_PASSWORD: CHANGEME
      MYSQL_ROOT_PASSWORD: CHANGEME
      MYSQL_USER: drupaluser
      TZ: America/New_York
    volumes:
    - /home/randall/volumes/d8-staff/mysql:/var/lib/mysql
    - /home/randall/volumes/d8-staff/db_autoimport:/docker-entrypoint-initdb.d/
    command:
    - --default-authentication-plugin=mysql_native_password
