version: '3.7'

volumes:
  db_data:

networks:
  db_network:
    driver: bridge

services:
  webapp:
    image: libapps-admin.uncw.edu:8000/randall-dev/d8-staff/drupal8base:apache
    container_name: webapp
    env_file: .env
    volumes:
      - ./drupal8docker/config/drupal/composer.json:/var/www/html/composer.json
      - ./drupal8docker/config/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./drupal8docker/sync:/drupal_sync
      - ./drupal8docker/themes/custom/:/var/www/html/web/themes/custom/
      - ./drupal8docker/modules/custom:/var/www/html/web/modules/custom/
    ports:
      - "8112:80"
    networks:
      - db_network
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0.16
    container_name: db
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db_autoimport:/docker-entrypoint-initdb.d/
    networks:
      - db_network
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  pma:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: pma
    env_file: .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_ARBITRARY: 0
      PMA_PORT: 3306
    networks:
      - db_network
    volumes:
      - /sessions
    depends_on:
      - db
    restart: always
    ports:
      - "8113:80"
