sids:
  uncw: uncw
authenticationMode: 2
loginUIUsernameTxt: 'Your UNCW username (email without the @uncw.edu)'
loginUIPasswordTxt: 'Your UNCW password (email)'
ldapUserHelpLinkUrl: 'https://uncw.edu/passwordreset/'
ldapUserHelpLinkText: 'Forgot password?'
emailOption: 3
emailUpdate: 2
emailTemplateHandling: none
emailTemplate: '@username@example.com'
emailTemplateUsageResolveConflict: false
emailTemplateUsageNeverUpdate: false
emailTemplateUsagePromptUser: false
emailTemplateUsageRedirectOnLogin: false
emailTemplateUsagePromptRegex: '.*@example\\.com'
passwordOption: 2
allowOnlyIfTextInDn: {  }
excludeIfTextInDn: {  }
excludeIfNoAuthorizations: 0
langcode: en
_core:
  default_config_hash: hSFOSjTAPcCBordJmChil6mui8q7uLwYfc5STlXL0yY
