sids:
  uncw: uncw
authenticationMode: exclusive
loginUIUsernameTxt: 'Your UNCW username (email without the @uncw.edu)'
loginUIPasswordTxt: 'Your UNCW password (email)'
ldapUserHelpLinkUrl: 'https://uncw.edu/passwordreset/'
ldapUserHelpLinkText: 'Forgot password?'
emailOption: disable
emailUpdate: update
emailTemplateHandling: none
emailTemplate: '@username@example.com'
emailTemplateUsageResolveConflict: false
emailTemplateUsageNeverUpdate: false
emailTemplateUsagePromptUser: false
emailTemplateUsageRedirectOnLogin: false
emailTemplateUsagePromptRegex: '.*@example\\.com'
passwordOption: disable
allowOnlyIfTextInDn: {  }
excludeIfTextInDn: {  }
excludeIfNoAuthorizations: false
langcode: en
_core:
  default_config_hash: hSFOSjTAPcCBordJmChil6mui8q7uLwYfc5STlXL0yY
skipAdministrators: false
